# ┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
# │                                        CEYBYTE POS                                               │
# │                                                                                                  │
# │                              Development Docker Compose                                          │
# │                                                                                                  │
# │  Description: Docker Compose configuration optimized for development workflow.                   │
# │               Includes hot reload, debugging, and development tools.                             │
# │                                                                                                  │
# │  Author: Akash Hasendra                                                                          │
# │  Copyright: 2025 Ceybyte.com - Sri Lankan Point of Sale System                                   │
# │  License: MIT License with Sri Lankan Business Terms                                             │
# └──────────────────────────────────────────────────────────────────────────────────────────────────┘

version: '3.8'

services:
  # Python FastAPI Backend (Development)
  ceybyte-api-dev:
    build:
      context: ./src-tauri/python-api
      dockerfile: Dockerfile
    container_name: ceybyte-pos-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/ceybyte_pos.db
      - JWT_SECRET_KEY=dev-secret-key-not-for-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80
      - FASTAPI_ENV=development
      - DEBUG=true
    volumes:
      - ./src-tauri/python-api:/app
      - api_dev_data:/app/data
    networks:
      - ceybyte-dev-network
    command: >
      sh -c "
        pip install watchdog &&
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  # React Frontend (Development with Hot Reload)
  ceybyte-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ceybyte-pos-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_APP_NAME=CeybytePOS Dev
      - VITE_COMPANY_NAME=Ceybyte.com
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - ceybyte-api-dev
    networks:
      - ceybyte-dev-network

  # Database Admin (Optional)
  ceybyte-db-admin:
    image: adminer:latest
    container_name: ceybyte-pos-db-admin
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    networks:
      - ceybyte-dev-network
    profiles:
      - admin

volumes:
  api_dev_data:
    driver: local

networks:
  ceybyte-dev-network:
    driver: bridge